"""Generate portable MoonBit tests from pinned RFC 6570 JSON fixtures.

The generated file is committed so `moon test --target all` needs no Python or
network access. Regenerate only after reviewing a fixture update and its license.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SUITE = ROOT / "testdata" / "uritemplate-test"
OUTPUT = ROOT / "conformance_generated_test.mbt"
FILES = [
    "spec-examples.json",
    "spec-examples-by-section.json",
    "extended-tests.json",
    "negative-tests.json",
]


def quote(value: str) -> str:
    result = ['"']
    for char in value:
        code = ord(char)
        if char == "\\":
            result.append("\\\\")
        elif char == '"':
            result.append('\\"')
        elif char == "\n":
            result.append("\\n")
        elif char == "\r":
            result.append("\\r")
        elif char == "\t":
            result.append("\\t")
        elif code < 32 or code == 127:
            result.append(f"\\u{{{code:X}}}")
        else:
            result.append(char)
    result.append('"')
    return "".join(result)


def scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return value
    raise TypeError(f"unsupported scalar: {type(value).__name__}")


def binding(name: str, value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, list):
        items = ", ".join(quote(scalar(item)) for item in value)
        body = f"List([{items}])"
    elif isinstance(value, dict):
        items = ", ".join(
            f"({quote(key)}, {quote(scalar(item))})"
            for key, item in value.items()
            if item is not None
        )
        body = f"Assoc([{items}])"
    else:
        body = f"Scalar({quote(scalar(value))})"
    return f"({quote(name)}, {body})"


def generate() -> str:
    lines = [
        "// Generated by tools/generate_conformance.py from pinned Apache-2.0 fixtures.",
        "// Edit the generator or source fixtures, then regenerate this file.",
        "",
    ]
    for filename in FILES:
        document = json.loads((SUITE / filename).read_text(encoding="utf-8"))
        for group_name, group in document.items():
            is_negative = filename == "negative-tests.json"
            title = f"{filename}: {group_name}"
            lines += ["///|", f"test {quote(title)} {{"]
            lines += [
                "  let bindings : Array[(String, @moonuritemplate.Value)] = ["
            ]
            for name, value in group["variables"].items():
                rendered = binding(name, value)
                if rendered is not None:
                    lines.append(f"    {rendered},")
            lines.append("  ]")
            if is_negative:
                lines.append("  let invalid : Array[String] = [")
                for source, _ in group["testcases"]:
                    lines.append(f"    {quote(source)},")
                lines += [
                    "  ]",
                    "  for source in invalid {",
                    "    let rejected = match @moonuritemplate.parse(source) {",
                    "      Err(_) => true",
                    "      Ok(template) => template.expand(bindings) is Err(_)",
                    "    }",
                    "    if !rejected { fail(\"accepted invalid fixture: \" + source) }",
                    "  }",
                ]
            else:
                lines.append("  let cases : Array[(String, Array[String])] = [")
                for source, expected in group["testcases"]:
                    alternatives = (
                        expected if isinstance(expected, list) else [expected]
                    )
                    rendered = ", ".join(quote(option) for option in alternatives)
                    lines.append(f"    ({quote(source)}, [{rendered}]),")
                lines += [
                    "  ]",
                    "  for case in cases {",
                    "    let (source, alternatives) = case",
                    "    let template = match @moonuritemplate.parse(source, strict_literals=false) {",
                    "      Ok(value) => value",
                    "      Err(_) => fail(\"cannot parse fixture: \" + source)",
                    "    }",
                    "    let output = match template.expand(bindings) {",
                    "      Ok(value) => value",
                    "      Err(_) => fail(\"cannot expand fixture: \" + source)",
                    "    }",
                    "    if !alternatives.contains(output) {",
                    "      fail(\"fixture mismatch: \" + source + \" => \" + output)",
                    "    }",
                    "  }",
                ]
            lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
